---
- name: "update packages"
  become: true
  apt:
      update_cache: yes
      autoremove: yes

- name: "upgrade packages"
  become: true
  apt:
      upgrade: yes

- name: "install nodeJs & npm"
  become: true
  apt:
      name: ["nodejs" , "npm"]
      state: latest

- name: "install pm2"
  become: true
  shell: npm install pm2 -g
