- name: "create directory"
  become: true
  file:
      path: ~/backend
      state: directory

- name: "push zip files"
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: ~/backend/artifact.tar.gz

- name: "unarchive artifact"
  become: true
  shell: |
      cd ~/backend
      tar xvfz artifact.tar.gz

- name: "push zip files"
  become: true
  copy:
      src: ~/project/artifact.tar.gz
      dest: ~/backend/artifact.tar.gz

- name: "constuct env file"
  become: true
  shell: |
      cp ~/backend/development.env ~/backend/.env

- name: "start web server"
  become: true
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
